--JOIN 실습문제
--1번
SELECT EMP_NAME, EMP_NO, DEPT_TITLE , JOB_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID=E.DEPT_CODE) 
JOIN JOB USING (JOB_CODE)
WHERE SUBSTR(EMP_NO,1,1)='7'
AND 
SUBSTR(EMP_NO,8,1)='2'
AND 
SUBSTR(EMP_NAME,1,1)='전';
--2번
SELECT EMP_ID , EMP_NAME , JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';
--3번
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE 
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID=E.DEPT_CODE) 
JOIN JOB USING (JOB_CODE)
WHERE DEPT_TITLE IN ('해외영업2부', '해외영업1부');
--4번
SELECT EMP_NAME, BONUS, DEPT_TITLE , LOCAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID=E.DEPT_CODE)
JOIN LOCATION L ON (D.LOCATION_ID=L.LOCAL_CODE)
WHERE BONUS IS NOT NULL;
--5번
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME 
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID=E.DEPT_CODE) 
JOIN JOB USING (JOB_CODE)
JOIN LOCATION L ON (D.LOCATION_ID=L.LOCAL_CODE)
WHERE DEPT_ID IS NOT NULL;
--6번--하이거 왜 안되냐ㅠㅠㅠㅠ질문하기..(미완성)
SELECT EMP_NAME , JOB_NAME, SALARY, 
SALARY*(1+BONUS)*12 연봉
FROM EMPLOYEE E
JOIN JOB J USING (JOB_CODE)
JOIN SAL_GRADE USING (SAL_LEVEL)
WHERE SALARY > (
SELECT MIN_SAL
FROM EMPLOYEE E
JOIN JOB J USING (JOB_CODE)
JOIN SAL_GRADE USING (SAL_LEVEL)
GROUP BY SAL_LEVEL 
)
GROUP BY SAL_LEVEL;
--7번
SELECT EMP_NAME 사원명, DEPT_TITLE 부서명, 
LOCAL_NAME 지역명 , 
DECODE(LOCAL_NAME, 'ASIA1', '한국', '일본') 국가명
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID=E.DEPT_CODE)
JOIN LOCATION L ON (D.LOCATION_ID=L.LOCAL_CODE)
WHERE NATIONAL_CODE IN ('KO', 'JP');
--8번
SELECT 
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON (E1.DEPT_CODE=E2.DEPT_CODE)






