-- 05 SUBQUERY 실습문제
--1번
SELECT EMP_ID , EMP_NAME 
, PHONE, HIRE_DATE 
FROM EMPLOYEE e 
WHERE DEPT_CODE =
(
SELECT DEPT_CODE 
FROM EMPLOYEE e2 
WHERE EMP_NAME='전지연'
)
AND 
EMP_NAME !='전지연';
--2번
SELECT EMP_ID , EMP_NAME , PHONE , SALARY , 
JOB_NAME
FROM EMPLOYEE
JOIN JOB j USING (JOB_CODE)
WHERE SALARY =(
SELECT MAX(SALARY)
FROM EMPLOYEE 
WHERE EXTRACT(YEAR FROM HIRE_DATE)>=2000
);
--3번
SELECT EMP_ID , EMP_NAME , DEPT_CODE , JOB_CODE 
, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT d ON (DEPT_ID=DEPT_CODE)
WHERE (DEPT_CODE, JOB_CODE)=(
SELECT DEPT_CODE, JOB_CODE
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME ='노옹철'
)
AND EMP_NAME !='노옹철';
--4번
SELECT EMP_ID , EMP_NAME , DEPT_CODE 
, JOB_CODE , HIRE_DATE 
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE (DEPT_CODE, JOB_CODE)=(
SELECT DEPT_CODE, JOB_CODE
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE)=2000
);
--5번
SELECT EMP_NO , EMP_NAME , DEPT_CODE , 
MANAGER_ID , EMP_NO , HIRE_DATE 
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID )=(
SELECT DEPT_CODE, MANAGER_ID
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 1,2)='77'
AND 
SUBSTR(EMP_NO, 8,1)='2'
);
--6번 --전형돈씨가 안나오는 문제 발생!(미완성)
SELECT EMP_ID, EMP_NAME, 
NVL(DEPT_TITLE, '소속없음'), JOB_NAME
, HIRE_DATE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT d ON (DEPT_ID=DEPT_CODE)
JOIN JOB USING (JOB_CODE)
WHERE HIRE_DATE IN (
SELECT MIN(HIRE_DATE)
FROM EMPLOYEE
GROUP BY DEPT_CODE
)
AND ENT_YN='N'
ORDER BY HIRE_DATE;
--7번 --미완성(질문하기!!!)
SELECT 
FROM EMPLOYEE e 
JOIN JOB USING (JOB_CODE)
WHERE SUBSTR(EMP_NO,1,2 ) IN (
SELECT MAX(TO_NUMBER(SUBSTR(EMP_NO, 1,2)))
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
GROUP BY JOB_CODE 
)




 










