--1번
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;
--2번
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN ='Y'
ORDER BY TO_NUMBER(SUBSTR(STUDENT_SSN, 1,6)) DESC;
--3번
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번 , STUDENT_ADDRESS "거주지 주소" 
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '%강원도%' 
OR STUDENT_ADDRESS LIKE  '%경기도%'
AND 
STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NAME;
--4번
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='법학과'
ORDER BY TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1,6));
--5번
--TO_CHAR(1, 'FM9.00') ->1.00
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00')
FROM TB_GRADE 
--WHERE TERM_NO, CLASS_NO = ('200402','C3118100');
WHERE TERM_NO = '200402'
AND CLASS_NO ='C3118100'
ORDER BY POINT DESC, STUDENT_NO ;
--6번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
FROM TB_DEPARTMENT 
JOIN TB_STUDENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;
--7번
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);
--8번
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);
--9번 
SELECT CLS.CLASS_NAME , PRO.PROFESSOR_NAME
FROM TB_CLASS CLS
JOIN TB_CLASS_PROFESSOR CPRO ON (CLS.CLASS_NO = CPRO.CLASS_NO)
JOIN TB_PROFESSOR PRO ON (CPRO.PROFESSOR_NO=PRO.PROFESSOR_NO)
JOIN TB_DEPARTMENT TD ON (TD.DEPARTMENT_NO=CLS.DEPARTMENT_NO)
WHERE CATEGORY ='인문사회'
ORDER BY CLS.CLASS_NAME ;
--10번
SELECT STUDENT_NO 학번, STUDENT_NAME "학생 이름"
,ROUND(AVG(POINT), 1) "전체 평점" 
FROM TB_STUDENT 
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NO ='059'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO; --SELECT문 중에 그룹함수 외의 조회하는 컬럼 모두를 GROUP BY에 써야한다
--11번
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름
, PROFESSOR_NAME 지도교수이름 
FROM TB_DEPARTMENT DEPT
JOIN TB_STUDENT STU ON (DEPT.DEPARTMENT_NO=STU.DEPARTMENT_NO)
JOIN TB_PROFESSOR PRO ON (PRO.PROFESSOR_NO=STU.COACH_PROFESSOR_NO)
WHERE STUDENT_NO='A313047';
--12번
SELECT STUDENT_NAME, TERM_NO
FROM TB_GRADE GR 
JOIN TB_STUDENT STU ON (STU.STUDENT_NO=GR.STUDENT_NO)
JOIN TB_CLASS CLA ON (CLA.CLASS_NO=GR.CLASS_NO)
WHERE TO_NUMBER(SUBSTR(TERM_NO, 1,4))=2007
AND 
CLASS_NAME ='인간관계론'
ORDER BY STUDENT_NAME;
--13번 -->>일단 과목번호로 차집합했는데
--과목이름만 나오도록 어떻게 하지..?과목이름-과목이름 해야하는데
--TB_CLASS_PROFESSOR에는 과목이름이 없고 과목번호만 있어효
SELECT CLA.CLASS_NO , CLA.CLASS_NAME, DEPT.DEPARTMENT_NAME
FROM TB_CLASS CLA 
JOIN TB_DEPARTMENT DEPT ON 
(CLA.DEPARTMENT_NO=DEPT.DEPARTMENT_NO)
WHERE CATEGORY='예체능'
MINUS 
SELECT CPRO.CLASS_NO,CLA.CLASS_NAME , DEPT.DEPARTMENT_NAME 
FROM TB_CLASS CLA 
JOIN TB_DEPARTMENT DEPT ON 
(CLA.DEPARTMENT_NO=DEPT.DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR CPRO ON 
(CPRO.CLASS_NO=CLA.CLASS_NO);

--14번--학생수 다르게 나옴!!!
SELECT STUDENT_NAME 학생이름, 
NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT STU 
JOIN TB_PROFESSOR PRO 
ON (STU.COACH_PROFESSOR_NO=PRO.PROFESSOR_NO)
JOIN TB_DEPARTMENT DEPT
ON (DEPT.DEPARTMENT_NO=STU.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='서반아어학과'
ORDER BY STUDENT_NO DESC;
--15번--이것도 미완성....
SELECT STUDENT_NO 학번, STUDENT_NAME 이름
, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT DEPT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN='N'
GROUP BY STUDENT_NO
HAVING AVG(POINT)>=4;

--16번--미완성
SELECT 
FROM TB_GRADE 
--17번
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT TB1
JOIN TB_STUDENT TB2 USING (DEPARTMENT_NO)
WHERE








