--1번
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;
--2번
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN ='Y'
ORDER BY TO_NUMBER(SUBSTR(STUDENT_SSN, 1,6)) DESC;
--3번
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번 , STUDENT_ADDRESS "거주지 주소" 
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '%강원도%' 
OR STUDENT_ADDRESS LIKE  '%경기도%'
AND 
STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NAME;
--4번
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='법학과'
ORDER BY TO_NUMBER(SUBSTR(PROFESSOR_SSN, 1,6));
--5번
--TO_CHAR(1, 'FM9.00') ->1.00
SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00')
FROM TB_GRADE 
--WHERE TERM_NO, CLASS_NO = ('200402','C3118100');
WHERE TERM_NO = '200402'
AND CLASS_NO ='C3118100'
ORDER BY POINT DESC, STUDENT_NO ;
--6번
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
FROM TB_DEPARTMENT 
JOIN TB_STUDENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;
--7번
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);
--8번
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);
--9번 ->이건 이 순서대로 JOIN하되, USING으로 하지말고 ON으로 해서
-- 각 테이블에 별칭 줘서 구체화해서 수정해보기
-- 오류내용 : SQL Error [918] [42000]: ORA-00918: 열의 정의가 애매합니다
--계열(TB_DEPARTMENT), 과목명(TB-CLASS), 교수이름(TB_PROFESSOR)
--학과번호, 
-- PROFESSOR랑 DEPARTMENT가 겹쳐서
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY='인문사회'
ORDER BY CLASS_NAME ;
--TB_CLASS -CLASS_NO> TB_CLASS_PROFESSOR
--PROFESSOR_NO->
/*과목번호 학과번호 과목이름 과목 구분 -> TB_CLASS
 * 계열 학과번호 학과이름 -> TB_DEPARTMENT
 * 교수이름 학과번호 -> TB_PROFESSOR*/




