--PDF2
--1번
SELECT STUDENT_NO , STUDENT_NAME ,
ENTRANCE_DATE 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE;
--2번
SELECT PROFESSOR_NAME, 
PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME) !='3';
--3번(미완성)
--만 나이 : 생일 지나야 한살씩 커지는 것
--교수의 생일, 오늘 날짜 비교 ->MONTHS_BETWEEN
SELECT PROFESSOR_NAME 교수이름 ,
TRUNC(MONTHS_BETWEEN(SYSDATE,
TO_DATE(19||SUBSTR(PROFESSOR_SSN, 1,6)))/12)  "나이"
--SUBSTR(PROFESSOR_SSN, 1,6)는 CHAR인데 DATE로 바꿔줘야함 ->TO_DATE로 감싸기
--|| : 이어쓰기 -> 50년이 안넘는 사람들은 2050년으로 계산됨
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1)='1' 
ORDER BY 나이;
--4번(이거 왜 결과 행 개수가 다르게 나오지)->이름이 네글자인 사람이 두명 있었어서!!
SELECT SUBSTR(PROFESSOR_NAME, 2) "이름" --두 번째 칸부터 길이를 지정하거나
--길이 지정 안하는 경우, 자동으로 끝까지 자르는 것으로 됨
FROM TB_PROFESSOR 
WHERE LENGTH(PROFESSOR_NAME)='3';
--이름이 네 글자인 경우도 동일하게 이름 부분만 나오게하고 싶으면->선택함수 이용
SELECT 
CASE 
	WHEN LENGTH(PROFESSOR_NAME)=3
	THEN SUBSTR(PROFESSOR_NAME,2)
	
	WHEN LENGTH(PROFESSOR_NAME)=4
	THEN SUBSTR(PROFESSOR_NAME,3)
END 이름
FROM TB_PROFESSOR;

--5번(미완성)
--이건 만나이가 아닌, 그냥 연도만 빼서 하면 된다
--주민등록번호와 입학일자 이용
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
-TO_NUMBER(19||SUBSTR(STUDENT_SSN,1,2))>19;
--EXTRACT : 날짜에서 원하는 것만 뽑아서 정수로 반환받는 것
--생년을 뽑아서 앞에 19를 붙이면 1998 이런식으로 문자열이 되는데
--그걸 TO_NUMBER 해서 숫자로 바꿈
--버전2
		
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)
 - EXTRACT(YEAR FROM TO_DATE('19'||SUBSTR(STUDENT_SSN, 1, 6),'YYYYMMDD')) > 19;	
--6번
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO NOT LIKE 'A%';
--7번
SELECT ROUND(AVG(POINT), 1)
FROM TB_GRADE 
WHERE STUDENT_NO ='A517178';